theme: jekyll-theme-minimal
title: George Donnelly
description: My life mission is universal liberty and prosperity. I'm focused on media, Bitcoin Cash, science fiction writing, business, satyagraha and personal development. Let's do this. You in or what?
logo: https://georgedonnelly.works/assets/img/logo2.png
google_analytics: UA-39670730-7
show_downloads: false


