theme: jekyll-theme-minimal
title: Meet George Donnelly
description: Full information on what George Donnelly is working on, how to connect and plug into projects. The mission is universal prosperity and liberty.
logo: https://georgedonnelly.works/assets/img/logo.png
google_analytics: UA-39670730-7