theme: jekyll-theme-minimal
title: George Donnelly
description: Name\: George Donnelly. Mission\: universal prosperity and liberty. Method\: blogs, vlogs, $BCH Bitcoin Cash, science fiction, business, satyagraha, discipline, wilpower and faith.
logo: https://georgedonnelly.works/assets/img/logo.png
google_analytics: UA-39670730-7
show_downloads: false